---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2021-05-13 - 12:25:14 +0000
    app.openshift.io/vcs-url: https://github.com/talaraujo/quarkus-demo.git
    app.quarkus.io/commit-id: a43eb845e1f74d6eda6c5c46b06cf549d25b8bc7
    app.quarkus.io/vcs-url: https://github.com/talaraujo/quarkus-demo.git
  labels:
    app.kubernetes.io/name: getting-started
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: getting-started
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: getting-started
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2021-05-13 - 12:25:14 +0000
    app.openshift.io/vcs-url: https://github.com/talaraujo/quarkus-demo.git
    app.quarkus.io/commit-id: a43eb845e1f74d6eda6c5c46b06cf549d25b8bc7
    app.quarkus.io/vcs-url: https://github.com/talaraujo/quarkus-demo.git
  labels:
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/name: getting-started
    app.openshift.io/runtime: quarkus
  name: getting-started
spec: {}
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: s2i-java
spec:
  dockerImageRepository: fabric8/s2i-java
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2021-05-13 - 12:25:14 +0000
    app.openshift.io/vcs-url: https://github.com/talaraujo/quarkus-demo.git
    app.quarkus.io/commit-id: a43eb845e1f74d6eda6c5c46b06cf549d25b8bc7
    app.quarkus.io/vcs-url: https://github.com/talaraujo/quarkus-demo.git
  labels:
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/name: getting-started
    app.openshift.io/runtime: quarkus
  name: getting-started
spec:
  output:
    to:
      kind: ImageStreamTag
      name: getting-started:1.0.0-SNAPSHOT
  source:
    binary: {}
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: s2i-java:2.3
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2021-05-13 - 12:25:14 +0000
    app.openshift.io/vcs-url: https://github.com/talaraujo/quarkus-demo.git
    app.quarkus.io/commit-id: a43eb845e1f74d6eda6c5c46b06cf549d25b8bc7
    app.quarkus.io/vcs-url: https://github.com/talaraujo/quarkus-demo.git
  labels:
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/name: getting-started
    app.openshift.io/runtime: quarkus
  name: getting-started
spec:
  replicas: 1
  selector:
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/name: getting-started
  template:
    metadata:
      annotations:
        app.quarkus.io/build-timestamp: 2021-05-13 - 12:25:14 +0000
        app.openshift.io/vcs-url: https://github.com/talaraujo/quarkus-demo.git
        app.quarkus.io/commit-id: a43eb845e1f74d6eda6c5c46b06cf549d25b8bc7
        app.quarkus.io/vcs-url: https://github.com/talaraujo/quarkus-demo.git
      labels:
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/name: getting-started
        app.openshift.io/runtime: quarkus
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: JAVA_APP_JAR
          value: /deployments/getting-started-1.0.0-SNAPSHOT-runner.jar
        image: taraujo/getting-started:1.0.0-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: getting-started
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - getting-started
      from:
        kind: ImageStreamTag
        name: getting-started:1.0.0-SNAPSHOT
    type: ImageChange
